### PR TITLE
AMA-961: Added template pages and corresponding _assets. 

### PR DESCRIPTION
**Pull request by TurRil**
Updated test templates and added helper pages to navigate site.

Incorporates https://github.com/cilt-uct/Brightspace-HTML-Templates/pull/4

1.     Added 2 new banners.
2.     updated footer style.
3.     Replaced line.png to amathuba_logo.png in footer
4.     Deleted video template page.

### CODE REVIEW

**Comment by smarquard** [comment]
Hmm: Files changed 1,825

Why is this such a massive PR? Do we need the whole of fontawesome checked in here?

**Comment by TurRil** [comment]
> Hmm: Files changed 1,825
> 
> Why is this such a massive PR? Do we need the whole of fontawesome checked in here?

It is to stay consistent with the version of the template - essentially each version contains the third party styles and scripts that it uses. This means that a lesson page created with V3/V2/V1 will still work later on when it is copied.

**Comment by smarquard** [comment]
Please discuss with me before updating anything on production.

**Comment by smarquard** [comment]
My issue with this is that where have a versioned set of assets for a 3rd-party lib, e.g. fontawesome-free-5.9.0-web we shouldn't also version that under a template version. It's not like it's going to change and it's a massive duplication of files that makes template updates very large when they should be very small.

**Pull request merged**
